#!/usr/bin/env python3
"""Regenerate PallaDrive's DRIVE-MAP.md.

SOUL.md points at `_system-files/DRIVE-MAP.md` as the authoritative map and
explicitly does NOT carry a folder list itself — because a map baked into an
identity file goes stale within days and gets trusted anyway. This script is
what keeps that promise true.

DERIVATION job (see cron-creator): no dedupe key. The idempotency contract is
that running twice with no change to the drive produces a byte-identical file
apart from the generated_at stamp.

Usage: gen_drive_map.py <palladrive-root> [-o OUTPUT]
"""
import argparse
import datetime as dt
import os
import sys

SKIP_DIRS = {".obsidian", ".trash", ".git", "__pycache__", ".DS_Store"}
SKIP_FILES = {".DS_Store"}


def human(n):
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f}{unit}" if unit == "B" else f"{n:.1f}{unit}"
        n /= 1024
    return f"{n:.1f}TB"


def walk(root):
    tree = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        rel = os.path.relpath(dirpath, root)
        if rel == ".":
            rel = ""
        if any(part in SKIP_DIRS for part in rel.split(os.sep)):
            continue
        files = []
        for f in sorted(filenames):
            if f in SKIP_FILES or f.startswith("."):
                continue
            try:
                size = os.path.getsize(os.path.join(dirpath, f))
            except OSError:
                size = 0
            files.append((f, size))
        tree[rel] = files
    return tree


def render(root, tree):
    stamp = dt.datetime.now().replace(microsecond=0).isoformat()
    total_files = sum(len(v) for v in tree.values())
    total_bytes = sum(s for v in tree.values() for _, s in v)

    out = []
    out.append("# PallaDrive — map")
    out.append("")
    out.append("> **GENERATED FILE — do not hand-edit.**")
    out.append("> Regenerated by `gen_drive_map.py`. Hand edits are lost on the next run.")
    out.append(f"> **Generated:** {stamp}")
    out.append(f"> **Totals:** {total_files} files, {human(total_bytes)}")
    out.append("")
    out.append("This is the map SOUL.md points at. SOUL deliberately carries no folder")
    out.append("list of its own — a map written into an identity file goes stale and")
    out.append("gets trusted anyway. Read this file when you need to know what is in")
    out.append("the drive. If the generated stamp above looks old, say so rather than")
    out.append("assuming the contents are current.")
    out.append("")
    out.append("---")
    out.append("")

    for rel in sorted(tree):
        files = tree[rel]
        label = rel if rel else "(drive root)"
        depth = rel.count(os.sep) + 1 if rel else 0
        out.append(f"{'#' * min(depth + 2, 6)} `{label}/`" if rel else "## `/` (drive root)")
        if not files:
            out.append("")
            out.append("_empty_")
            out.append("")
            continue
        out.append("")
        out.append("| File | Size |")
        out.append("|---|---|")
        for f, s in files:
            out.append(f"| `{f}` | {human(s)} |")
        out.append("")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("-o", "--output", default=None)
    a = ap.parse_args()
    root = os.path.abspath(os.path.expanduser(a.root))
    if not os.path.isdir(root):
        sys.exit(f"not a directory: {root}")
    out_path = a.output or os.path.join(root, "_system-files", "DRIVE-MAP.md")
    text = render(root, walk(root))
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(text)
    print(f"wrote {out_path} ({len(text)} chars)")


if __name__ == "__main__":
    main()
